version: '3.6'
services:
  mainnet:
    container_name: dcore-mainnet
    image: yangwao/decent-docker:mainnet-manual-1.2.2
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data:/root/.decent/data
    ports:
     - "127.0.0.1:8090:8090"
     - "127.0.0.1:8091:8091"
     - "127.0.0.1:8093:8093"

  publictestnet:
    container_name: dcore-publictestnet
    image: yangwao/decent-docker:publictestnet-manual-1.2.2
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_publictestnet:/root/testnet_data
    ports:
     - "127.0.0.1:18090:8090"
     - "127.0.0.1:18091:8091"
     - "127.0.0.1:18093:8093"

  customnet:
    image: yangwao/decent-docker:publictestnet-manual-1.2.2
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_customnet:/root/testnet_data
    ports:
     - "127.0.0.1:28090:8090"
     - "127.0.0.1:28091:8091"
     - "127.0.0.1:28093:8093"

  cliwallet:
    container_name: dcore-cliwallet
    image: yangwao/decent-docker:cliwallet-manual-1.2.2
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_cliwallet:/root/testnet_data
    ports:
     - "127.0.0.1:38091:8091"
     - "127.0.0.1:38093:8093"
    command: ["/decent-bin/cli_wallet", "--server-rpc-endpoint=ws://dcore-publictestnet:8090", "--rpc-endpoint=0.0.0.0:8091", "--rpc-http-endpoint=0.0.0.0:8093", "--daemon"]
